Minor
UPDATE

diff --git a/dns-server b/dns-server
--- a/dns-server
+++ b/dns-server
@@ -18,10 +18,10 @@ if [[ -z $isRunning ]] || [[ $isRunning -le 1 ]]; then
 	echo "dns starting"
 	DNS_BINARY=$(which dnsproxy)
 	echo $DNS_BINARY
-	if [[ -z $DNS_BINARY ]]; then
-		echo "$DNS_BINARY DNS_BINARY not found; exiting please reinstall binary"
-		exit 123
-	fi
+#	if [[ -z $DNS_BINARY ]]; then
+#		echo "$DNS_BINARY DNS_BINARY not found; exiting please reinstall binary"
+#		exit 123
+#	fi
 	(
 			launchctl stop com.apple.mDNSResponder.reloaded
 			PRE_STOP_DNS
