Minor update to lg and er

diff --git a/dns-server b/dns-server
--- a/dns-server
+++ b/dns-server
@@ -18,10 +18,10 @@ if [[ -z $isRunning ]] || [[ $isRunning -le 1 ]]; then
 	echo "dns starting"
 	DNS_BINARY=$(which dnsproxy)
 	echo $DNS_BINARY
-#	if [[ -z $DNS_BINARY ]]; then
-#		echo "$DNS_BINARY DNS_BINARY not found; exiting please reinstall binary"
-#		exit 123
-#	fi
+	if [[ -z $DNS_BINARY ]]; then
+		echo "$DNS_BINARY DNS_BINARY not found; exiting please reinstall binary"
+		exit 123
+	fi
 	(
 			launchctl stop com.apple.mDNSResponder.reloaded
 			PRE_STOP_DNS
@@ -32,10 +32,10 @@ if [[ -z $isRunning ]] || [[ $isRunning -le 1 ]]; then
 			--cache --cache-size 168190 \
 			--fallback 35.192.105.158 --fallback 35.232.120.211 --fallback 8.8.8.8 --fallback 8.8.4.4 \
 			--fallback 1.1.1.1 --fallback 1.0.0.1 \
-			--port 53 --port 5053 --https-port=443 --verbose >> $LOG_FILE_DNS_SERVER
+			--port 53 --port 5053 --https-port=443 --verbose \
+			--output $LOG_FILE_DNS_SERVER 2>&1 >> $LOG_FILE_DNS_SERVER
 			launchctl start com.apple.mDNSResponder.reloaded
-		 )>>$LOG_FILE_DNS_SERVER.out
-#			--output $LOG_FILE_DNS_SERVER
+		 )2>&1 >>$LOG_FILE_DNS_SERVER.out
 fi
 dig www.google.com @192.168.123.9
 dig www.google.com @192.168.123.8
